#!/usr/bin/env python3
"""Interaction and layout tests of the HTML prototype only. No Swift or server claims."""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json,sys,platform,argparse,hashlib,datetime
R=Path(__file__).resolve().parents[1]
ap=argparse.ArgumentParser();ap.add_argument('--chromium',default='/usr/bin/chromium');ap.add_argument('--write-report',action='store_true');args=ap.parse_args()
checks=[];js_errors=[];matrix=[]
def ck(name,ok,detail=None):
 checks.append({'name':name,'passed':bool(ok),'detail':detail})
 if not ok:print('FAIL',name,detail,flush=True)
with sync_playwright() as pw:
 browser=pw.chromium.launch(executable_path=args.chromium,args=['--no-sandbox'])
 page=browser.new_page(viewport={'width':1600,'height':1120});page.set_default_timeout(4000);page.on('pageerror',lambda err:js_errors.append(str(err)))
 html=(R/'DESIGN/APPLICATION.html').read_text(encoding='utf-8')
 def load():page.goto('about:blank');page.set_content(html);page.wait_for_timeout(30)
 def a():return page.evaluate('window.drivy.app.state()')
 def m():return page.evaluate('window.drivy.state()')
 def show(route):page.evaluate('(v)=>window.drivy.app.show(v)',route)
 def click(action,id=None):page.locator(f'#device [data-ui="{action}"]'+(f'[data-id="{id}"]' if id else '')).filter(visible=True).last.click()
 def fill(id,value):page.fill('#'+id,value)
 load();ck('Home is default application entry',a()['route']=='home');ck('Staff tabs follow canonical IA',page.locator('#device .app-navigation button').all_text_contents()==['Séance','Agenda','Élèves','École'])
 click('map','capture');ck('Home enters existing map without reconstructing observations',m()['view']=='capture' and len(m()['events'])==3)
 page.locator('#device [data-action=signal]').click();page.locator('#device [data-category]').first.click();page.locator('#device .sheet [data-status=ATTENTION]').click()
 page.locator('#device [data-action=exit]').click();ck('Leaving map preserves capture and added observation',a()['route']=='home' and m()['capture']=='recording' and len(m()['events'])==4)
 click('tab','students');fill('studentSearch','Ines');ck('Search matches accents and keeps input focus',page.locator('#studentsResults .ui-row').count()==1 and page.evaluate('document.activeElement.id')=='studentSearch')
 click('student','ines');click('tab','agenda');click('tab','students');ck('Tab restores prior detail and person',a()['route']=='student' and a()['selectedStudent']=='ines')
 click('back');ck('Back restores search text and result',page.locator('#studentSearch').input_value()=='Ines' and page.locator('#studentsResults .ui-row').count()==1)
 fill('studentSearch','nobody');ck('Empty search is not a network error','Aucun résultat' in page.locator('#device').inner_text());click('clear-search');click('filter');click('set-filter','A');ck('Formation filter has two matches',page.locator('#studentsResults .ui-row').count()==2);ck('Filter dialog closes and restores focus',a()['modal'] is None and page.evaluate('document.activeElement.dataset.ui')=='filter')
 click('student','emma');page.select_option('[data-input=training]','A');ck('Training A does not borrow B lesson or reports','Pas de leçon pour cette formation.' in page.locator('#device').inner_text());click('student-reports');ck('Training with no report stays empty','Aucun bilan partagé pour cette formation' in page.locator('#device').inner_text());click('dismiss')
 load();click('tab','agenda');click('start-plan');fill('planTime','11:30');click('review-plan');ck('Review does not reserve or mutate a lesson',len(a()['lessons'])==5);click('commit-plan');ck('Pause overlap yields conflict without reservation',len(a()['lessons'])==5 and 'plus disponible' in page.locator('#device').inner_text());click('dismiss');ck('Conflict preserves form values',page.locator('#planTime').input_value()=='11:30');fill('planTime','09:00');click('review-plan');click('commit-plan');ck('Explicit confirmation adds one lesson and updates agenda',len(a()['lessons'])==6 and a()['route']=='agenda' and a()['day']==23)
 click('lesson','local-6');click('reschedule','local-6');fill('planTime','10:30');click('back');ck('Leaving touched planning requires a consequence choice',a()['modal']['type']=='discard-plan');click('discard-plan');ck('Discarding keeps original reservation',a()['lessons'][-1]['time']=='09:00')
 load();show('planning');page.select_option('#stateSelect','offline');ck('Offline reservation visibly unavailable',page.locator('#device [data-ui=review-plan]').is_disabled() and 'Connexion requise' in page.locator('#device').inner_text());fill('planPlace','Autre rendez-vous');page.select_option('#stateSelect','normal');ck('Connection change preserves draft fields',page.locator('#planPlace').input_value()=='Autre rendez-vous');fill('planPlace','');click('review-plan');ck('Form error associated to a permanent label',page.locator('#planPlace').get_attribute('aria-invalid')=='true' and page.locator('#planPlace-error').count()==1)
 load();show('planning');page.check('#planConflict');click('review-plan');click('commit-plan');ck('Injected last-minute conflict gives no fake success',len(a()['lessons'])==5 and a()['modal']['type']=='review-plan' and a()['toast'] is None)
 load();show('report');before=a()['published'];fill('observationText','Texte <script> & nuance pédagogique.');click('include-observation','report18-1');click('preview');ck('Preview does not publish',a()['published']==before);ck('Preview shows only selected report observation',page.locator('#device [data-component="DS07.observation-row"]').count()==1);ck('Live session events are not borrowed by completed lesson report',all(x['id'].startswith('report18-') for x in page.evaluate('reportSnapshot(true).observations')))
 ck('User text escaped rather than parsed',page.locator('#device').inner_text().find('Texte <script> & nuance pédagogique.')>=0)
 click('ask-publish');ck('Explicit publication confirmation names recipient','Emma Laurent' in page.locator('.workspace-modal').inner_text());click('publish');ck('Publication is an explicit copied projection',a()['published']['observationText']=='Texte <script> & nuance pédagogique.' and len(a()['published']['observations'])==1 and 'selected' not in a()['published'] and 'visibility' not in a()['published']['observations'][0]);ck('Publishing does not alter private live events',len(m()['events'])==3 and all(x['visibility']=='PRIVATE' for x in m()['events']))
 snap=a()['published'];show('report');fill('observationText','Nouvelle version non publiée.');ck('Subsequent draft edits cannot mutate shared snapshot',a()['published']==snap)
 page.select_option('#stateSelect','offline');click('save-draft');ck('Offline draft saves locally and not publicly',a()['savedDraft']['observationText']=='Nouvelle version non publiée.' and a()['published']==snap);click('preview');ck('Offline publish is disabled with reason',page.locator('[data-ui=ask-publish]').is_disabled() and 'Connexion requise pour publier.' in page.locator('#device').inner_text())
 load();show('report');page.select_option('#stateSelect','save-error');click('save-draft');ck('Failed local save retains text and stays unsaved',a()['savedDraft'] is None and 'non enregistré' in page.locator('#device').inner_text());page.select_option('#stateSelect','normal');fill('nextStep','');click('preview');ck('Incomplete draft cannot publish',page.locator('[data-ui=ask-publish]').is_disabled())
 load();show('documents');click('document','doc3');ck('Unanalysed document has no preview',page.locator('.document-thumb').count()==0 and 'en analyse' in page.locator('.workspace-modal').inner_text());click('dismiss');click('document','doc2');ck('Ready fixture has a preview',page.locator('.document-thumb').count()==1);click('dismiss');click('add-document');page.locator('#documentUpload').set_input_files({'name':'piece-test.pdf','mimeType':'application/pdf','buffer':b'fake local test document'});ck('Upload simulation never auto-validates permit',a()['documents'][-1]['status']=='ANALYZING' and a()['documents'][-1]['humanStatus'] is None)
 load();show('students');click('filter');page.locator('.workspace-modal button').last.focus();page.keyboard.press('Tab');ck('Workspace sheet traps keyboard focus',page.evaluate('document.activeElement===document.querySelector(".workspace-modal button")'));ck('Underlying content inert in workspace sheet',page.locator('.workspace-base[inert]').count()==1);page.keyboard.press('Escape');ck('Escape closes and returns to originating action',a()['modal'] is None and page.evaluate('document.activeElement.dataset.ui')=='filter')
 show('account');page.select_option('#appearance','dark');ck('Account appearance uses SAME map tokens',m()['theme']=='dark' and page.locator('#device').get_attribute('data-theme')=='dark');click('tab','home');click('map','capture');ck('Appearance persists across workspace and map',page.locator('#device').get_attribute('data-theme')=='dark')
 load();page.select_option('#roleSelect','learner');ck('Learner canonical tabs',page.locator('.app-navigation button').all_text_contents()==['Mes leçons','Agenda','Mon parcours']);ck('Learner cannot enter staff report route via router',page.evaluate("(()=>{window.drivy.app.show('report');return window.drivy.app.state().route})()")=='learner');ck('Learner has no staff live controls',page.locator('#device [data-action=signal]').count()==0);show('shared');ck('Shared read has no publish or draft tools',page.locator('#device [data-ui=publish],#device [data-ui=preview],#device [data-ui=save-draft]').count()==0)
 show('progress');page.select_option('[data-input=training]','A');ck('Learner training switch has isolated empty state','Pas encore d’évaluation' in page.locator('#device').inner_text())
 load();show('agenda');page.select_option('#pageStateSelect','error');ck('Page error distinct from empty and retryable','Chargement impossible' in page.locator('#device').inner_text() and 'Aucune leçon' not in page.locator('#device').inner_text());click('retry-page');ck('Page retry restores fixture rather than fabricated zero',page.locator('#device .lesson-row').count()==3)
 # Each real workspace screen rendered with 4 sizes,2 themes,2 font scales.
 load();routes=['home','agenda','students','student','lesson','planning','report','preview','shared','documents','account','notifications','school','learner','learner-agenda','progress']
 for route in routes:
  for size in ['phone','small','tablet-compact','tablet']:
   for theme in ['light','dark']:
    for scale in ['normal','large']:
     page.evaluate('p=>{window.drivy.app.role(p.route.startsWith("learner")?"learner":"staff");window.drivy.set({size:p.size,theme:p.theme,scale:p.scale,reduced:true});window.drivy.app.show(p.route)}',{'route':route,'size':size,'theme':theme,'scale':scale})
     page.wait_for_timeout(15)
     result=page.locator('#device').evaluate('''el=>{const visible=x=>x.getBoundingClientRect().width>0&&x.getBoundingClientRect().height>0;const boxes=[...el.querySelectorAll('button,input,select,textarea')].filter(visible);const undersized=boxes.filter(x=>{const b=x.getBoundingClientRect();return b.width<43.5||b.height<43.5}).map(x=>({tag:x.tagName,action:x.dataset.ui||x.id,w:x.getBoundingClientRect().width,h:x.getBoundingClientRect().height}));const sc=el.querySelector('.workspace-body');const clipped=[...sc.querySelectorAll('h1,h2,strong,small,label,.rowtext,.ui-button span')].filter(visible).filter(x=>!x.classList.contains('sr-only')).filter(x=>x.scrollWidth>x.clientWidth+2&&getComputedStyle(x).display!=='inline').map(x=>({text:x.innerText.slice(0,65),width:x.clientWidth,scroll:x.scrollWidth}));const nav=el.querySelector('.app-navigation').getBoundingClientRect(),d=el.getBoundingClientRect();return {horizontal:sc.scrollWidth>sc.clientWidth+2,undersized,clipped,navVisible:nav.left>=d.left&&nav.right<=d.right+1&&nav.bottom<=d.bottom&&nav.top>=d.top}}''')
     matrix.append({'route':route,'size':size,'theme':theme,'scale':scale,**result})
 ck('Workspace layout matrix',all(not x['horizontal'] and not x['undersized'] and not x['clipped'] and x['navVisible'] for x in matrix),[x for x in matrix if x['horizontal'] or x['undersized'] or x['clipped'] or not x['navVisible']])
 # Reuse regression checks assert actual function-bound component markers in both worlds.
 load();show('agenda');ck('Agenda uses canonical appointment renderer',page.locator('[data-component="DS04"]').count()==3);show('student');ck('Dossier uses canonical training selector',page.locator('[data-component="DS06"]').count()==1);show('report');ck('Report uses common observation row',page.locator('[data-component="DS07.observation-row"]').count()==2)
 page.evaluate("window.drivy.view('capture')");page.locator('[data-action=list]').click();ck('Map observation list uses the SAME observation component',page.locator('[data-component="DS07.observation-row"]').count()==3)
 ck('No Javascript exceptions',not js_errors,js_errors)
 browser.close()
report={'version':'3.17','scope':'HTML workspace + inherited map regression, not native','passed':all(x['passed'] for x in checks),'interactionChecks':len(checks),'layoutCombinations':len(matrix),'checks':checks,'matrix':matrix,'environment':{'python':platform.python_version(),'system':platform.platform(),'browser':args.chromium,'loading':'set_content; file URL separately blocked by administrator'},'native':'NOT_EXECUTED','server':'NOT_EXECUTED','userTests':'NOT_EXECUTED'}
if args.write_report:(R/'annexes/verification-application-v3-17.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({k:report[k] for k in ['passed','interactionChecks','layoutCombinations']},indent=2))
sys.exit(0 if report['passed'] else 1)
