'use strict';
const F=__FIXTURE__;
const TOKENS=__TOKENS_JSON__;
const MAP=__MAP_JSON__;
const DENSE_MAP=__DENSE_MAP_JSON__;
const paths={
 close:'M6 6l12 12M6 18L18 6',back:'M15 5l-7 7 7 7',chevron:'M9 5l7 7-7 7',plus:'M12 5v14M5 12h14',
 pin:'M19 9c0 5-7 12-7 12S5 14 5 9a7 7 0 0 1 14 0ZM14 9a2 2 0 1 1-4 0 2 2 0 0 1 4 0Z',
 flag:'M5 21V4m0 0c5-4 9 4 14 0v10c-5 4-9-4-14 0',
 location:'M21 3L14 21l-3-8-8-3Z',pause:'M8 5v14M16 5v14',stop:'M6 6h12v12H6Z',play:'M8 5l11 7-11 7Z',
 prev:'M6 6v12M18 6l-9 6 9 6Z',next:'M18 6v12M6 6l9 6-9 6Z',
 check:'M5 12l4 4L19 6',attention:'M12 5v9M12 19h.01',rework:'M7 7l10 10M7 17L17 7',
 more:'M5 12h.01M12 12h.01M19 12h.01',list:'M9 6h12M9 12h12M9 18h12M3 6h.01M3 12h.01M3 18h.01',
 lock:'M7 10V7a5 5 0 0 1 10 0v3M5 10h14v11H5ZM12 14v3',
 info:'M12 11v6M12 7h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',
 offline:'M2 2l20 20M8.5 8.5a13 13 0 0 1 11.5 1M4 10l-2-2M7 13a8 8 0 0 1 7-2M10 16a3 3 0 0 1 4 0M12 20h.01',
 gpsOff:'M3 3l18 18M9 5a7 7 0 0 1 10 4c0 1.8-.9 3.8-2 5.7M6 7a7 7 0 0 0-1 3c0 5 7 11 7 11l2.4-2.5',
 clock:'M12 7v6l4 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z',
 priority:'M12 21V3M3 12h18M17 8l4 4-4 4M9 6l3-3 3 3',parking:'M7 21V3h6a5 5 0 0 1 0 10H7',
 sign:'M11 13v9M4 3h16v10H4ZM7 6h10M7 10h6',roundabout:'M8 5a8 8 0 0 1 10 2l2 3M20 5v5h-5M20 14a8 8 0 0 1-9 6l-3-1M11 23l-3-4 4-2M5 18a8 8 0 0 1-2-10l2-3M1 6l4-1 1 5',
 eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7-10-7-10-7ZM15 12a3 3 0 1 1-6 0 3 3 0 0 1 6 0Z',
 anticipate:'M4 19l6-7 4 3 6-11M14 4h6v6',route:'M5 17a3 3 0 1 1 0 6 3 3 0 0 1 0-6ZM19 1a3 3 0 1 1 0 6 3 3 0 0 1 0-6ZM5 17v-5h14V7',
 edit:'M4 20l4-1 12-12-3-3L5 16ZM14 7l3 3',trash:'M4 6h16M9 6V3h6v3M6 6l1 15h10l1-15M10 10v7M14 10v7',reset:'M4 8a9 9 0 1 1-1 8M4 3v5h5'
};
const icon=(name,extra='')=>`<svg xmlns="http://www.w3.org/2000/svg" class="icon ${extra}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.info}"/></svg>`;
const e=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=s=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const statuses={ATTENTION:{label:'Attention',icon:'attention'},TO_REWORK:{label:'À retravailler',icon:'rework'},POSITIVE:{label:'Point positif',icon:'check'}};
const theme=id=>F.themes.find(x=>x.id===id);
const themeTitle=x=>x.kind==='MARKER'?'Moment à qualifier':(theme(x.theme)?.label||'Observation');
const statusTitle=x=>statuses[x.status]?.label||'Repère';
const tone=x=>`<span class="tone-icon ${x.status||''}">${icon(statuses[x.status]?.icon||'pin')}</span>`;
const themeGlyph=x=>x?.kind==='QUALIFIED'?(theme(x.theme)?.icon||'info'):'pin';
const themeTone=x=>`<span class="theme-tone ${x.status||''}">${icon(themeGlyph(x))}</span>`;
const device=document.getElementById('device');
let S={mapDetail:'calm',denseFixtures:false,view:'capture',sheet:null,pending:null,events:structuredClone(F.observations),nextId:4,elapsed:F.durationSeconds,second:674,selected:'demo-02',playing:false,speed:1,capture:'recording',environment:'normal',theme:'light',size:'phone',scale:'normal',reduced:false,highcontrast:false,toast:null,saveError:false,pan:{x:0,y:0},zoom:1,follow:true,editing:null,lessonEnded:false};
let toastTimer=null,lastTick=null,focusReturn=null,drag=null,firstTick=true;
function pointAt(t){const a=F.points;for(let i=1;i<a.length;i++){if(t<=a[i].t){const p=a[i-1],q=a[i],r=Math.max(0,Math.min(1,(t-p.t)/(q.t-p.t)));return{x:p.x+(q.x-p.x)*r,y:p.y+(q.y-p.y)*r}}}return{x:a.at(-1).x,y:a.at(-1).y}}
function hasAnchor(){return S.environment!=='no-gps'&&S.capture==='recording'&&!S.lessonEnded}
function pendingContext(){return{second:S.elapsed,capturedAt:new Date(Date.parse(F.baseTime)+S.elapsed*1000).toISOString(),anchor:hasAnchor()?pointAt(S.elapsed):null,theme:null}}
function applyPrefs(){Object.assign(device.dataset,{theme:S.theme,size:S.size,scale:S.scale,reduced:String(S.reduced),highcontrast:String(S.highcontrast),mapDetail:S.mapDetail,capture:S.capture});for(const[k,v]of Object.entries(TOKENS.colors[S.theme]))device.style.setProperty('--'+k,v);document.getElementById('themeSelect').value=S.theme;document.getElementById('sizeSelect').value=S.size;document.getElementById('stateSelect').value=S.environment;document.getElementById('textLarge').checked=S.scale==='large';document.getElementById('motionReduced').checked=S.reduced;document.getElementById('contrastHigh').checked=S.highcontrast;document.getElementById('mapDetailSelect').value=S.mapDetail;document.getElementById('denseFixtures').checked=S.denseFixtures;if(reducedMotion())device.getAnimations({subtree:true}).forEach(a=>a.cancel());}
function stateLabel(){return S.lessonEnded?'Leçon terminée':S.capture==='stopped'?'GPS arrêté':S.capture==='paused'?'GPS en pause':S.environment==='no-gps'?'Sans GPS':'GPS actif'}
function systemBar(){return `<div class="systembar" aria-hidden="true"><span>9:41</span><span class="system-icons"><svg viewBox="0 0 20 12"><path d="M2 10V8M7 10V6M12 10V3M17 10V1" stroke="currentColor" stroke-width="3"/></svg><svg viewBox="0 0 20 12"><path d="M2 3q8-6 16 0M5 6q5-4 10 0M8 9q2-2 4 0" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg><svg class="battery" viewBox="0 0 26 12"><rect x="1" y="1" width="21" height="10" rx="2.5" fill="none" stroke="currentColor" opacity=".45"/><rect x="3" y="3" width="17" height="6" rx="1.2" fill="currentColor"/><path d="M24 4v4" stroke="currentColor" stroke-width="2"/></svg></span></div>`}
function head(){const replay=S.view==='replay';return `<header class="head surface"><button class="round" data-action="${replay?'backLive':'exit'}" aria-label="${replay?'Revenir à la leçon':'Fermer la carte sans arrêter la leçon'}">${icon(replay?'back':'close')}</button><div class="identity"><strong>${replay?'Replay':e(F.student)}</strong><small>${replay?`${icon('lock')} Privé · Emma Laurent`:`<span class="state-dot"></span><span id="captureState">${stateLabel()}</span>`}</small></div>${replay?'':`<div class="elapsed" aria-label="Durée de la leçon, ${fmt(S.elapsed)}">${fmt(S.elapsed)}</div>`}<button class="round" data-action="more" aria-label="Commandes de la leçon et aide">${icon('more')}</button></header>`}
function banner(){if(S.saveError&&!S.sheet)return `<div class="state-banner error" role="alert">${icon('attention')}<span>Repère non enregistré</span></div>`;if(S.environment==='offline')return `<div class="state-banner" role="status">${icon('offline')}<span>Hors ligne · envoi en attente</span></div>`;if(S.environment==='send-error')return `<div class="state-banner error" role="alert">${icon('attention')}<span>Envoi en échec</span><button data-action="retrySend">Réessayer</button></div>`;return ''}
function viewToPixel(p){const w=device.clientWidth,h=device.clientHeight,scale=Math.max(w/390,h/844);return{x:(w-390*scale)/2+p.x*scale,y:(h-844*scale)/2+p.y*scale}}
function pinInner(x,selected){
 const glyph=selected?themeGlyph(x):(statuses[x.status]?.icon||'pin');
 return `<span class="pin-glyph" data-glyph="${glyph}">${icon(glyph)}</span>${selected&&x.status?`<span class="pin-status" aria-hidden="true">${icon(statuses[x.status].icon)}</span>`:''}`;
}
function pins(){return S.events.filter(x=>x.anchor).map(x=>{
 const p=viewToPixel(x.anchor),selected=S.view==='replay'&&S.selected===x.id;
 return `<button class="map-hit ${selected?'selected':''}" style="left:${p.x}px;top:${p.y}px" data-event="${x.id}" data-status="${x.status||'MARKER'}" data-selected="${selected}" aria-pressed="${selected}" aria-label="${e(themeTitle(x))}, ${e(statusTitle(x))}, ${fmt(x.second)}, observation privée"><span class="pin-content">${pinInner(x,selected)}</span></button>`;
}).join('')}
function refreshPins(){device.querySelectorAll('.map-hit').forEach(b=>{
 const x=S.events.find(x=>x.id===b.dataset.event);if(!x)return;
 const selected=S.view==='replay'&&S.selected===x.id;
 if(b.dataset.selected!==String(selected)){b.classList.toggle('selected',selected);b.dataset.selected=String(selected);b.setAttribute('aria-pressed',String(selected));b.querySelector('.pin-content').innerHTML=pinInner(x,selected);}
});}
function mapScene(){const route=F.points.map((p,i)=>`${i?'L':'M'}${p.x} ${p.y}`).join(' '),p=pointAt(S.view==='replay'?S.second:S.elapsed);return `<div class="map-viewport" id="mapViewport" role="group" aria-label="Trajet fictif. Les observations sont accessibles dans la liste et la chronologie."><div class="map-layer" id="mapLayer">${S.mapDetail==='dense'?DENSE_MAP:MAP}<svg class="route-art" viewBox="0 0 390 844" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><path d="${route}" fill="none" stroke="var(--routeHalo)" stroke-width="9" stroke-linejoin="round" stroke-linecap="round"/><path d="${route}" fill="none" stroke="var(--route)" stroke-width="5" stroke-linejoin="round" stroke-linecap="round"/><circle cx="${F.points[0].x}" cy="${F.points[0].y}" r="6" fill="var(--surface)" stroke="var(--accent)" stroke-width="3"/><g id="positionDot" transform="translate(${p.x} ${p.y})"><circle r="18" fill="var(--accent)" opacity=".13"/><circle r="8" fill="var(--accent)" stroke="var(--surface)" stroke-width="3"/></g></svg><div id="mapPins">${pins()}</div></div></div>`}
function noGpsScene(){return `<section class="no-gps-area"><div class="no-gps-content">${icon('clock')}<h2>Leçon sans GPS</h2><p>Les observations sont liées au temps.</p><div class="no-gps-moments">${S.events.slice(-2).map(x=>`<div><span>${fmt(x.second)}</span><strong>${e(themeTitle(x))}</strong></div>`).join('')}</div></div></section>`}
function mapTools(){return `<div class="map-tools ${S.view==='replay'?'replay-tools':''}" id="mapTools"><span class="free" ${S.follow?'hidden':''}>Vue libre</span><button class="round surface" data-action="recenter" aria-label="Recentrer sur le point du trajet sélectionné">${icon('location')}</button></div>`}
function dock(){return `<section class="dock" aria-label="Actions de la leçon"><button class="observation-link" data-action="list" aria-label="${S.events.length} observations privées">${icon('list')}<span class="count">${S.events.length} observation${S.events.length>1?'s':''}</span>${icon('lock')}<span class="end">${icon('chevron')}</span></button><div class="capture-actions">${UI.button('Signaler',`data-action="signal" ${S.lessonEnded?'disabled':''}`,'primary','plus','signal-button')}<button class="mark-button" data-action="mark" aria-label="Marquer un moment sans le qualifier" ${S.lessonEnded?'disabled':''}>${icon('pin')}</button></div></section>`}
function replayDock(){const x=S.events.find(x=>x.id===S.selected);return `<section class="dock replay-dock" aria-label="Replay privé"><div class="selected-observation" id="selectedObservation">${selectedMarkup(x)}</div><div class="timeline"><div class="timeline-track"></div><div class="timeline-fill" id="timeFill" style="width:${S.second/S.elapsed*100}%"></div>${S.events.map(x=>`<span class="timeline-marker ${x.id===S.selected?'selected':''}" data-event="${x.id}" style="left:${Math.min(100,x.second/S.elapsed*100)}%"></span>`).join('')}<input id="timeline" type="range" min="0" max="${S.elapsed}" value="${S.second}" step="1" aria-label="Position dans le replay" aria-valuetext="${fmt(S.second)} sur ${fmt(S.elapsed)}"/></div><div class="time-labels"><span id="replayTime">${fmt(S.second)}</span><span>${fmt(S.elapsed)}</span></div><div class="replay-buttons"><button data-action="list" aria-label="Liste des observations privées">${icon('list')}</button><div class="button-group"><button data-action="previous" aria-label="Observation précédente">${icon('prev')}</button><button class="play-button" data-action="play" aria-label="${S.playing?'Mettre le replay en pause':'Lire le replay'}">${icon(S.playing?'pause':'play')}</button><button data-action="next" aria-label="Observation suivante">${icon('next')}</button></div><button class="speed" data-action="speed" aria-label="Vitesse du replay : ${S.speed} fois">×${S.speed}</button></div></section>`}
function selectedMarkup(x){return x?`${themeTone(x)}<div class="selected-text"><strong>${e(themeTitle(x))}</strong><small>${e(statusTitle(x))} · ${fmt(x.second)} ${icon('lock')}</small></div><button class="round" data-action="detail" aria-label="Détails et modification de cette observation">${icon('more')}</button>`:`<div class="selected-text"><strong>Le trajet</strong><small>Aucune observation sélectionnée</small></div>`}
function toastMarkup(){if(!S.toast)return '';const x=S.events.find(x=>x.id===S.toast.id);if(!x)return '';return `<aside class="notice-toast" role="status">${tone(x)}<div class="toast-text"><strong>${e(themeTitle(x))}</strong><small>${e(statusTitle(x))} · Privé</small></div><button data-action="undo" aria-label="${S.toast.previous?'Annuler la modification de cette observation':'Annuler l’ajout de cette observation'}">Annuler</button></aside>`}
function header(title,sub='',back=false){return UI.sheetHeader(title,{sub,back,closeLabel:'Fermer sans ajouter d’observation'})}
function modalMarkup(){if(!S.sheet)return '';let content='',p=S.pending,sub=p?`${icon(p.anchor?'pin':'clock')}${fmt(p.second)} · Privé`:'';
 if(S.sheet==='categories')content=header('Signaler',sub)+`<div class="sheet-body"><div class="category-grid">${F.themes.map(x=>`<button class="category" data-category="${x.id}" aria-label="${e(x.label)}"><span class="cat-icon">${icon(x.icon)}</span><span class="cat-label">${e(x.label)}</span></button>`).join('')}</div>${S.saveError?'<p class="sheet-error" role="alert">Repère non enregistré. Réessaie ou annule.</p>':''}</div><div class="sheet-footer"><button class="text-action" data-action="markPending">${icon('pin')}Marquer un moment</button></div>`;
 if(S.sheet==='status')content=header(theme(p?.theme)?.label||'Observation',sub,true)+`<div class="sheet-body"><div class="status-list">${Object.keys(statuses).map(k=>UI.statusAction(k,`data-status="${k}"`)).join('')}</div>${S.saveError?'<p class="sheet-error" role="alert">Non enregistrée. Réessaie ou annule.</p>':''}<p class="commit-hint">Le choix enregistre.</p></div>`;
 if(S.sheet==='session')content=header('La leçon')+`<div class="sheet-body"><p class="session-status">${stateLabel()} · ${fmt(S.elapsed)}</p><button class="session-row" data-action="pauseCapture" ${S.capture==='stopped'||S.lessonEnded?'disabled':''}>${icon(S.capture==='paused'?'play':'pause')}${S.capture==='paused'?'Reprendre le GPS':'Mettre le GPS en pause'}</button><button class="session-row danger" data-action="askStop" ${S.capture==='stopped'||S.lessonEnded?'disabled':''}>${icon('stop')}Arrêter le GPS</button><button class="session-row" data-action="openReplay">${icon('play')}Revoir le trajet</button><button class="session-row" data-action="help">${icon('info')}Comprendre le signalement</button><button class="session-row danger" data-action="askFinish" ${S.lessonEnded?'disabled':''}>${icon('check')}Terminer la leçon</button></div>`;
 if(S.sheet==='help')content=header('Le signalement')+`<div class="sheet-body"><p class="helptext">L’instant est retenu à l’ouverture. Choisis un thème puis un statut pour ajouter une observation privée. Annuler ne crée rien.</p><p class="helptext">Un repère garde seulement le moment. Les détails peuvent être complétés plus tard. Rien n’est noté ni publié automatiquement.</p><p class="helptext">Arrêter le GPS ne termine pas la leçon. Les observations restent possibles sans position.</p><p class="helptext">Utilise ces commandes dans des conditions adaptées. Le prototype ne valide pas leur sûreté en mouvement.</p></div>`;
 if(S.sheet==='list')content=header('Observations',`${icon('lock')}Privées · ${S.events.length}`)+`<div class="sheet-body">${S.events.length?S.events.map(x=>UI.observationRow(x,{attrs:`data-list-event="${x.id}"`})).join(''):'<p class="helptext">Aucune observation pour cette leçon.</p>'}</div>`;
 if(S.sheet==='detail'){const x=S.events.find(x=>x.id===S.editing);content=header(x?themeTitle(x):'Observation',x?`${icon('lock')}${fmt(x.second)} · Privé`:'')+`<div class="sheet-body">${x?`<p class="session-status">${e(statusTitle(x))}${x.anchor?'':' · Sans position'}</p>${UI.field('noteInput','Précision facultative',x.note||'',{multiline:true,attrs:'maxlength="2000"'})}${UI.button('Enregistrer','data-action="saveNote"','primary',null,'full-button')}<button class="session-row" data-action="changeQualification">${icon('edit')}${x.kind==='MARKER'?'Qualifier ce moment':'Modifier le thème et le statut'}</button><button class="session-row danger" data-action="removeEvent">${icon('trash')}Supprimer l’observation</button>`:''}</div>`}
 if(S.sheet==='stopConfirm')content=header('Arrêter le GPS ?')+`<div class="sheet-body"><p class="helptext">Le trajet sera arrêté. La leçon et les observations restent disponibles.</p><div class="confirm-actions"><button data-action="closeSheet">Continuer</button><button class="danger" data-action="stopCapture">Arrêter le GPS</button></div></div>`;
 if(S.sheet==='finishConfirm')content=header('Terminer la leçon ?')+`<div class="sheet-body"><p class="helptext">Le GPS sera arrêté. Le bilan ne sera pas publié automatiquement.</p><div class="confirm-actions"><button data-action="closeSheet">Continuer</button><button class="danger" data-action="finishLesson">Terminer la leçon</button></div></div>`;
 if(S.sheet==='exit')content=header('Quitter la carte ?')+`<div class="sheet-body"><p class="helptext">La capture et les observations sont conservées tant que cette démonstration reste ouverte.</p><p class="helptext">Le reste de la navigation de l’application n’est pas représenté dans cet atelier.</p><button class="full-button blue" data-action="closeSheet">Revenir à la leçon</button></div>`;
 return UI.dialog(content,{step:S.sheet});
}
function updateStudio(){
 document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===(S.sheet==='categories'?'categories':S.sheet==='status'?'status':S.view))));
 document.getElementById('previewTitle').textContent=({capture:'La carte de leçon',categories:'Les catégories',status:'Le statut',replay:'Le replay'}[S.sheet]||{capture:'La carte de leçon',replay:'Le replay'}[S.view]);
}
function reducedMotion(){return S.reduced||window.matchMedia('(prefers-reduced-motion: reduce)').matches;}
function render(focusSelector=null){
 applyPrefs();const mode=!!S.sheet;
 device.innerHTML=`<div class="app-base" ${mode?'inert aria-hidden="true"':''}>${S.environment==='no-gps'?noGpsScene():mapScene()}${systemBar()}${head()}${banner()}${S.environment==='no-gps'?'':mapTools()}${S.view==='replay'?replayDock():dock()}${toastMarkup()}</div>${modalMarkup()}<div class="home-indicator" aria-hidden="true"></div>`;
 applyTransform();updateStudio();
 if(focusSelector&&!firstTick)(device.querySelector(focusSelector)||device.querySelector(S.view==='replay'?'[data-action=play]':'[data-action=signal]'))?.focus({preventScroll:true});
 resizeInsets();firstTick=false;
}
function moveSignalStep(next,focusSelector,direction=1){
 const sheet=device.querySelector('.sheet');
 if(!sheet||!['categories','status'].includes(sheet.dataset.step)){S.sheet=next;render(focusSelector);return;}
 // Sample the interrupted presentation before cancelling it; reuse this exact dialog node.
 const before=sheet.getBoundingClientRect().height;
 sheet.getAnimations({subtree:true}).forEach(a=>a.cancel());
 S.sheet=next;
 const holder=document.createElement('template');holder.innerHTML=modalMarkup();
 const replacement=holder.content.querySelector('.sheet');
 sheet.innerHTML=replacement.innerHTML;sheet.dataset.step=next;
 const after=sheet.getBoundingClientRect().height;
 if(!reducedMotion()&&sheet.animate){
  const options={duration:200,easing:'cubic-bezier(.2,.8,.2,1)'};
  if(Math.abs(after-before)>.5)sheet.animate([{height:before+'px'},{height:after+'px'}],options);
  for(const part of sheet.querySelectorAll('.heading,.sheet-body'))part.animate([{opacity:.35,transform:`translateX(${direction*12}px)`},{opacity:1,transform:'translateX(0)'}],options);
 }
 updateStudio();(sheet.querySelector(focusSelector)||sheet.querySelector('button'))?.focus({preventScroll:true});
}

function resizeInsets(){requestAnimationFrame(()=>{const dockEl=device.querySelector('.dock'),tools=device.querySelector('.map-tools'),toast=device.querySelector('.notice-toast');if(dockEl&&tools)tools.style.bottom=(device.clientHeight-dockEl.offsetTop+18+(toast?toast.offsetHeight+12:0))+'px';if(dockEl&&toast)toast.style.bottom=(device.clientHeight-dockEl.offsetTop+14)+'px';const headEl=device.querySelector('.head'),ban=device.querySelector('.state-banner');if(headEl&&ban)ban.style.top=(headEl.offsetTop+headEl.offsetHeight+12)+'px'})}
function applyTransform(){const m=device.querySelector('#mapLayer');if(m)m.style.transform=`translate(${S.pan.x}px,${S.pan.y}px) scale(${S.zoom})`;const tag=device.querySelector('.map-tools .free');if(tag)tag.hidden=S.follow;}
function announce(text){document.getElementById('liveAnnounce').textContent='';requestAnimationFrame(()=>document.getElementById('liveAnnounce').textContent=text)}
function openSheet(name){focusReturn=document.activeElement?.dataset?.action||'signal';S.sheet=name;S.toast=null;clearTimeout(toastTimer);render('.sheet button');}
function closeSheet(){S.sheet=null;S.pending=null;S.editing=null;S.saveError=false;render(`[data-action="${focusReturn||'signal'}"]`)}
function beginSignal(){if(S.lessonEnded)return;S.pending=pendingContext();S.saveError=false;S.editing=null;openSheet('categories')}
function addEvent(kind,status=null){if(S.lessonEnded)return;const p=S.pending||pendingContext();if(kind==='QUALIFIED'&&(!p.theme||!statuses[status]))return;if(S.environment==='save-error'){S.saveError=true;if(S.sheet!=='status'){announce('Repère non enregistré. Échec simulé.');render(S.sheet?'[data-action=markPending]':'[data-action=mark]');return}render(`.sheet [data-status="${status}"]`);return}let x=S.events.find(x=>x.id===S.editing);const previous=x?structuredClone(x):null;if(!x){x={id:'demo-'+(S.nextId++),note:'',visibility:'PRIVATE'};S.events.push(x)}Object.assign(x,{second:p.second,capturedAt:p.capturedAt,anchor:p.anchor?{...p.anchor}:null,theme:kind==='QUALIFIED'?p.theme:null,status,kind});S.pending=null;S.sheet=null;S.editing=null;S.selected=x.id;S.saveError=false;S.toast={id:x.id,previous};render('[data-action=signal]');announce(`${themeTitle(x)}, ${statusTitle(x)}, ${previous?'modifiée':'ajoutée'} en mémoire de démonstration.`);clearTimeout(toastTimer);toastTimer=setTimeout(()=>{S.toast=null;device.querySelector('.notice-toast')?.remove();resizeInsets()},6500)}
function openReplay(id=null){S.view='replay';S.sheet=null;S.pending=null;S.editing=null;S.toast=null;S.playing=false;S.pan={x:0,y:0};S.zoom=1;S.follow=true;S.selected=id||S.events.find(x=>x.id==='demo-02')?.id||S.events[0]?.id||null;const x=S.events.find(x=>x.id===S.selected);S.second=x?.second||0;render('[data-action=play]')}
function switchView(v){S.playing=false;lastTick=null;S.sheet=null;S.pending=null;S.editing=null;S.saveError=false;S.pan={x:0,y:0};S.zoom=1;S.follow=true;if(v==='replay'){openReplay();return}S.view='capture';if(v==='categories'||v==='status'){S.pending=pendingContext();S.sheet=v;if(v==='status')S.pending.theme=F.themes[0].id}render(S.sheet?'.sheet button':'[data-action=signal]')}
function orderedEvents(){return S.events.map((x,index)=>({...x,_index:index})).sort((a,b)=>a.second-b.second||a._index-b._index);}
function nearestEvent(t){return S.events.map((x,index)=>({x,index,d:Math.abs(x.second-t)})).filter(v=>v.d<=8).sort((a,b)=>a.d-b.d||a.index-b.index)[0]?.x||null;}
function jump(dir){const items=orderedEvents(),index=items.findIndex(x=>x.id===S.selected);let x;
 if(index>=0&&Math.abs(items[index].second-S.second)<.1)x=items[Math.max(0,Math.min(items.length-1,index+dir))];
 else x=dir>0?items.find(x=>x.second>S.second+.1):items.filter(x=>x.second<S.second-.1).at(-1);
 if(!x)x=dir>0?items.at(-1):items[0];
 if(x){S.selected=x.id;S.second=x.second;updateReplay();announce(`${themeTitle(x)}, ${statusTitle(x)}, ${fmt(x.second)}`)}
}
function updateReplay(){const dot=device.querySelector('#positionDot'),p=pointAt(S.second);if(dot)dot.setAttribute('transform',`translate(${p.x} ${p.y})`);const t=device.querySelector('#replayTime');if(t)t.textContent=fmt(S.second);const r=device.querySelector('#timeline');if(r){if(document.activeElement!==r)r.value=S.second;r.setAttribute('aria-valuetext',`${fmt(S.second)} sur ${fmt(S.elapsed)}`)}const fill=device.querySelector('#timeFill');if(fill)fill.style.width=S.second/S.elapsed*100+'%';const obs=device.querySelector('#selectedObservation');if(obs&&obs.dataset.selected!==String(S.selected)){obs.innerHTML=selectedMarkup(S.events.find(x=>x.id===S.selected));obs.dataset.selected=String(S.selected);}refreshPins();device.querySelectorAll('.timeline-marker').forEach(m=>m.classList.toggle('selected',m.dataset.event===S.selected));}
function detail(id){S.editing=id||S.selected;S.playing=false;openSheet('detail')}
function act(a,b){switch(a){case'signal':beginSignal();break;case'closeSheet':closeSheet();break;case'sheetBack':{const previous=S.pending?.theme;if(S.pending)S.pending.theme=null;S.saveError=false;moveSignalStep('categories',previous?`[data-category="${previous}"]`:'.category',-1);break;}case'mark':S.pending=pendingContext();addEvent('MARKER');break;case'markPending':addEvent('MARKER');break;case'more':openSheet('session');break;case'list':openSheet('list');break;case'help':S.sheet='help';render('.sheet button');break;case'exit':openSheet('exit');break;case'backLive':S.view='capture';S.playing=false;S.selected=null;S.pan={x:0,y:0};S.zoom=1;S.follow=true;render('[data-action=signal]');break;case'openReplay':openReplay();break;case'recenter':S.pan={x:0,y:0};S.zoom=1;S.follow=true;applyTransform();announce('Vue du trajet recentrée.');break;case'undo':if(S.toast){if(S.toast.previous){const i=S.events.findIndex(x=>x.id===S.toast.id);if(i>=0)S.events[i]=S.toast.previous;}else S.events=S.events.filter(x=>x.id!==S.toast.id);S.toast=null;render(S.view==='replay'?'[data-action=play]':'[data-action=signal]');announce('Dernière modification annulée.')}break;case'pauseCapture':S.capture=S.capture==='paused'?'recording':'paused';S.sheet=null;render('[data-action=more]');announce(stateLabel());break;case'askStop':S.sheet='stopConfirm';render('.sheet button');break;case'stopCapture':S.capture='stopped';S.sheet=null;S.pending=null;render('[data-action=signal]');announce('GPS arrêté. La leçon continue.');break;case'askFinish':S.sheet='finishConfirm';render('.sheet button');break;case'finishLesson':S.lessonEnded=true;S.capture='stopped';S.sheet=null;S.pending=null;render('[data-action=more]');announce('Leçon terminée. Rien n’est publié.');break;case'play':S.playing=!S.playing;lastTick=null;b.setAttribute('aria-label',S.playing?'Mettre le replay en pause':'Lire le replay');b.innerHTML=icon(S.playing?'pause':'play');break;case'previous':jump(-1);break;case'next':jump(1);break;case'speed':S.speed=S.speed===1?2:S.speed===2?4:1;b.textContent='×'+S.speed;b.setAttribute('aria-label','Vitesse du replay : '+S.speed+' fois');break;case'detail':detail();break;case'saveNote':{const x=S.events.find(x=>x.id===S.editing);if(x)x.note=device.querySelector('#noteInput').value;S.sheet=null;S.editing=null;render('[data-action=detail]');announce('Précision conservée dans la démonstration.');break}case'changeQualification':{const x=S.events.find(x=>x.id===S.editing);if(!x)break;S.pending={second:x.second,anchor:x.anchor?{...x.anchor}:null,capturedAt:x.capturedAt,theme:null};S.sheet='categories';render('.category');break}case'removeEvent':{S.events=S.events.filter(x=>x.id!==S.editing);S.selected=null;S.sheet=null;S.editing=null;render('[data-action=list]');announce('Observation retirée de la démonstration.');break}case'retrySend':announce('Démonstration : nouvel essai toujours en échec. Aucun serveur n’est appelé.');break;}}
device.addEventListener('click',ev=>{const b=ev.target.closest('button,[data-action]');if(!b||b.disabled)return;if(b.dataset.category&&S.pending){S.pending.theme=b.dataset.category;moveSignalStep('status','[data-status]',1);return}if(b.dataset.status&&S.sheet==='status'){addEvent('QUALIFIED',b.dataset.status);return}if(b.dataset.event){if(S.view==='replay'){const x=S.events.find(x=>x.id===b.dataset.event);if(x){S.selected=x.id;S.second=x.second;updateReplay();announce(`${themeTitle(x)}, ${statusTitle(x)}, ${fmt(x.second)}`)}}else openReplay(b.dataset.event);return}if(b.dataset.listEvent){const x=S.events.find(x=>x.id===b.dataset.listEvent);if(x?.anchor&&S.environment!=='no-gps')openReplay(x.id);else detail(x?.id);return}if(b.dataset.action)act(b.dataset.action,b)});
device.addEventListener('input',ev=>{if(ev.target.id==='timeline'){S.second=+ev.target.value;const x=nearestEvent(S.second);S.selected=x?.id||null;updateReplay()}});
device.addEventListener('keydown',ev=>{if(S.sheet){if(ev.key==='Escape'){ev.preventDefault();closeSheet();return}if(ev.key==='Tab'){const a=[...device.querySelectorAll('.sheet button:not(:disabled),.sheet input,.sheet textarea,.sheet select')].filter(el=>el.getClientRects().length);if(!a.length)return;const first=a[0],last=a.at(-1);if(ev.shiftKey&&document.activeElement===first){ev.preventDefault();last.focus()}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first.focus()}}}});
device.addEventListener('pointerdown',ev=>{const map=ev.target.closest('.map-viewport');if(!map||ev.target.closest('button')||S.sheet||ev.button!==0)return;drag={id:ev.pointerId,x:ev.clientX,y:ev.clientY,baseX:S.pan.x,baseY:S.pan.y};map.setPointerCapture(ev.pointerId)});
device.addEventListener('pointermove',ev=>{if(!drag||drag.id!==ev.pointerId)return;const dx=ev.clientX-drag.x,dy=ev.clientY-drag.y;if(Math.abs(dx)+Math.abs(dy)<4)return;S.follow=false;S.pan={x:Math.max(-130,Math.min(130,drag.baseX+dx)),y:Math.max(-200,Math.min(200,drag.baseY+dy))};applyTransform()});
device.addEventListener('pointerup',()=>drag=null);device.addEventListener('pointercancel',()=>drag=null);
device.addEventListener('wheel',ev=>{if(!ev.target.closest('.map-viewport')||S.sheet)return;ev.preventDefault();S.zoom=Math.max(.9,Math.min(2.5,S.zoom+(ev.deltaY<0?.1:-.1)));S.follow=false;applyTransform()},{passive:false});
function tick(now){if(S.playing&&S.view==='replay'&&!S.sheet){if(lastTick!==null){S.second=Math.min(S.elapsed,S.second+(now-lastTick)/1000*S.speed);const held=S.events.find(x=>x.id===S.selected);if(!held||Math.abs(held.second-S.second)>8)S.selected=nearestEvent(S.second)?.id||null;updateReplay();if(S.second>=S.elapsed){S.playing=false;const b=device.querySelector('[data-action=play]');if(b){b.innerHTML=icon('play');b.setAttribute('aria-label','Lire le replay')}}}lastTick=now}else lastTick=null;requestAnimationFrame(tick)}
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>switchView(b.dataset.view)));
document.getElementById('themeSelect').addEventListener('change',ev=>{S.theme=ev.target.value;applyPrefs()});
document.getElementById('sizeSelect').addEventListener('change',ev=>{S.size=ev.target.value;render()});
document.getElementById('stateSelect').addEventListener('change',ev=>{S.environment=ev.target.value;S.pending=null;S.sheet=null;S.saveError=false;render()});
document.getElementById('textLarge').addEventListener('change',ev=>{S.scale=ev.target.checked?'large':'normal';render()});
document.getElementById('motionReduced').addEventListener('change',ev=>{S.reduced=ev.target.checked;applyPrefs()});
document.getElementById('contrastHigh').addEventListener('change',ev=>{S.highcontrast=ev.target.checked;applyPrefs()});
document.getElementById('mapDetailSelect').addEventListener('change',ev=>{S.mapDetail=ev.target.value;render()});
function setDensityFixture(enabled){
 S.denseFixtures=!!enabled;const ids=new Set(F.densityObservations.map(x=>x.id));
 S.events=S.events.filter(x=>!ids.has(x.id));if(enabled)S.events.push(...structuredClone(F.densityObservations));
 if(!S.events.some(x=>x.id===S.selected))S.selected=null;
 S.sheet=null;S.pending=null;S.editing=null;S.toast=null;S.playing=false;render();
 announce(enabled?'Quatre observations fictives rapprochées ajoutées pour la revue.':'Observations de densité retirées.');
}
document.getElementById('denseFixtures').addEventListener('change',ev=>setDensityFixture(ev.target.checked));
document.getElementById('resetDemo').addEventListener('click',()=>{S.events=structuredClone(F.observations);S.denseFixtures=false;S.mapDetail='calm';S.nextId=4;S.lessonEnded=false;S.capture='recording';S.environment='normal';S.toast=null;switchView('capture');announce('Démonstration réinitialisée avec trois observations fictives.')});
window.matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',()=>{if(reducedMotion())device.getAnimations({subtree:true}).forEach(a=>a.cancel())});
new ResizeObserver(()=>{const p=device.querySelector('#mapPins');if(p)p.innerHTML=pins();resizeInsets()}).observe(device);
// Test hooks and design exports: local-only, no persistence or network endpoints.
window.drivy={density:setDensityFixture,state:()=>structuredClone(S),set:patch=>{Object.assign(S,patch);render()},view:switchView,pointAt,fixture:F};
const params=new URLSearchParams(location.search);if(params.get('export')==='1')document.body.classList.add('export-mode');if(['small','phone','tablet','tablet-compact'].includes(params.get('size')))S.size=params.get('size');if(params.get('theme')==='dark')S.theme='dark';if(params.get('text')==='large')S.scale='large';S.reduced=params.get('motion')==='reduce';if(['normal','offline','no-gps','send-error','save-error'].includes(params.get('state')))S.environment=params.get('state');
if(params.get('map')==='dense')S.mapDetail='dense';if(params.get('density')==='1'){S.denseFixtures=true;S.events.push(...structuredClone(F.densityObservations));}
switchView(['capture','categories','status','replay'].includes(params.get('view'))?params.get('view'):'capture');requestAnimationFrame(tick);
