() => {
 const root=document.querySelector('#device'), rb=root.getBoundingClientRect(), NS='http://www.w3.org/2000/svg';
 const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=n=>Number(n.toFixed(3));let serial=0;
 function color(c){return c||'none'}
 function name(el){return (el.dataset.action||el.dataset.category||el.className?.baseVal||el.className||el.tagName).toString().replace(/[^a-zA-Z0-9_-]/g,'_')+'_'+(++serial)}
 function rect(el){const r=el.getBoundingClientRect();return{x:r.x-rb.x,y:r.y-rb.y,w:r.width,h:r.height}}
 function freezeSvg(el){const copy=el.cloneNode(true),originals=[el,...el.querySelectorAll('*')],copies=[copy,...copy.querySelectorAll('*')];for(let i=0;i<copies.length;i++){const c=getComputedStyle(originals[i]),n=copies[i];n.removeAttribute('class');n.removeAttribute('style');n.removeAttribute('aria-hidden');n.removeAttribute('id');for(const k of ['fill','stroke','stroke-width','stroke-linecap','stroke-linejoin','font-family','font-size','font-weight','letter-spacing','text-anchor','opacity']){const v=c.getPropertyValue(k);if(v)n.setAttribute(k,v)}}const r=rect(el);copy.setAttribute('x',num(r.x));copy.setAttribute('y',num(r.y));copy.setAttribute('width',num(r.w));copy.setAttribute('height',num(r.h));copy.setAttribute('overflow','visible');return new XMLSerializer().serializeToString(copy)}
 function textNode(n,parent){let out='';const c=getComputedStyle(parent),font=parseFloat(c.fontSize);if(!n.textContent.trim())return '';const rx=/\S+/gu;for(const m of n.textContent.matchAll(rx)){const range=document.createRange();range.setStart(n,m.index);range.setEnd(n,m.index+m[0].length);const r=range.getBoundingClientRect();if(r.width<.1||r.height<.1)continue;const x=r.x-rb.x,y=r.bottom-rb.y-font*.2;out+=`<text x="${num(x)}" y="${num(y)}" font-family="Arial, sans-serif" font-size="${num(font)}" font-weight="${c.fontWeight}" fill="${esc(c.color)}" letter-spacing="${esc(c.letterSpacing==='normal'?'0':c.letterSpacing)}">${esc(m[0])}</text>`}return out}
 function render(el){if(el.nodeType===Node.TEXT_NODE)return textNode(el,el.parentElement);if(el.nodeType!==Node.ELEMENT_NODE)return '';const c=getComputedStyle(el),r=rect(el);if(c.display==='none'||c.visibility==='hidden'||parseFloat(c.opacity)===0||el.classList.contains('sr-only'))return '';if(el.namespaceURI===NS)return freezeSvg(el);let result='';if(c.backgroundColor!=='rgba(0, 0, 0, 0)'&&c.backgroundColor!=='transparent'){let rad=parseFloat(c.borderTopLeftRadius)||0;if(c.borderTopLeftRadius.endsWith('%'))rad=Math.min(r.w,r.h)*rad/100;result+=`<rect x="${num(r.x)}" y="${num(r.y)}" width="${num(r.w)}" height="${num(r.h)}" rx="${num(Math.min(rad,r.w/2,r.h/2))}" fill="${esc(c.backgroundColor)}"/>`}
 const sides=['Top','Right','Bottom','Left'];let widths=sides.map(s=>parseFloat(c['border'+s+'Width'])||0);
 if(widths[0]>0&&widths.every(w=>w===widths[0])){let rad=parseFloat(c.borderTopLeftRadius)||0;if(c.borderTopLeftRadius.endsWith('%'))rad=Math.min(r.w,r.h)*rad/100;result+=`<rect x="${num(r.x+widths[0]/2)}" y="${num(r.y+widths[0]/2)}" width="${num(r.w-widths[0])}" height="${num(r.h-widths[0])}" rx="${num(rad)}" fill="none" stroke="${esc(c.borderTopColor)}" stroke-width="${widths[0]}"/>`}
 else for(let i=0;i<4;i++){if(!widths[i])continue;const pts=[[r.x,r.y,r.x+r.w,r.y],[r.x+r.w,r.y,r.x+r.w,r.y+r.h],[r.x,r.y+r.h,r.x+r.w,r.y+r.h],[r.x,r.y,r.x,r.y+r.h]][i];result+=`<path d="M${num(pts[0])} ${num(pts[1])}L${num(pts[2])} ${num(pts[3])}" stroke="${esc(c['border'+sides[i]+'Color'])}" stroke-width="${widths[i]}"/>`}
 if(el.matches('.status-option+.status-option'))result+=`<path d="M${num(r.x+52)} ${num(r.y)}H${num(r.x+r.w)}" stroke="${esc(getComputedStyle(root).getPropertyValue('--border').trim())}"/>`;
 if(el.tagName==='INPUT'&&el.type==='range'){const t=(el.value-el.min)/(el.max-el.min);result+=`<circle cx="${num(r.x+8+(r.w-16)*t)}" cy="${num(r.y+r.h/2-1)}" r="7" fill="${esc(getComputedStyle(root).getPropertyValue('--accent').trim())}" stroke="${esc(getComputedStyle(root).getPropertyValue('--surface').trim())}" stroke-width="3"/>`}
 for(const n of el.childNodes)result+=render(n);
 return `<g id="${name(el)}"${parseFloat(c.opacity)<1?` opacity="${c.opacity}"`:''}>${result}</g>`;
 }
 const style=getComputedStyle(root),rad=parseFloat(style.borderTopLeftRadius)||0;return `<svg xmlns="${NS}" width="${rb.width}" height="${rb.height}" viewBox="0 0 ${rb.width} ${rb.height}" fill="none"><title>Drivy V3.16 - ${document.querySelector('#previewTitle').textContent}</title><desc>Export vectoriel de maquette documentaire. Pas de capture native ni de fond cartographique réel. Les ombres CSS ne sont pas transférées.</desc><defs><clipPath id="screen"><rect width="${rb.width}" height="${rb.height}" rx="${rad}"/></clipPath></defs><g clip-path="url(#screen)">${render(root)}</g></svg>`;
}
