/* Navigation and fixtures for the non-map screens. No network, persistent storage or implicit publication. */
const WF=__WORKSPACE_FIXTURE__;
Object.assign(paths,{
 calendar:'M4 5h16v16H4ZM4 10h16M8 2v6M16 2v6M8 14h2M14 14h2M8 18h2',
 people:'M15 20v-2a5 5 0 0 0-10 0v2M10 3a4 4 0 1 1 0 8 4 4 0 0 1 0-8ZM18 4a3 3 0 0 1 0 6M18 14a4 4 0 0 1 4 4v2',
 person:'M20 21a8 8 0 0 0-16 0M12 3a4 4 0 1 1 0 8 4 4 0 0 1 0-8Z',
 school:'M4 21V8l8-5 8 5v13M2 21h20M9 21v-7h6v7M8 9h1M15 9h1',
 car:'M3 10l2-6h14l2 6M3 10h18v9H3ZM5 19v3M19 19v3M6 14h2M16 14h2',
 search:'M10 3a7 7 0 1 1 0 14 7 7 0 0 1 0-14ZM15 15l6 6',
 bell:'M6 9a6 6 0 0 1 12 0v6l2 3H4l2-3ZM10 21h4',
 file:'M5 2h9l5 5v15H5ZM14 2v6h5M8 12h8M8 16h6',
 filter:'M4 6h16M7 12h10M10 18h4',
 shield:'M12 2l8 3v6c0 5-8 11-8 11S4 16 4 11V5ZM8 11l3 3 5-6',
 globe:'M12 2a10 10 0 1 1 0 20 10 10 0 0 1 0-20ZM2 12h20M12 2c-6 5-6 15 0 20 6-5 6-15 0-20',
 moon:'M20 15A9 9 0 0 1 9 3a9 9 0 1 0 11 12Z',
 upload:'M12 16V3M7 8l5-5 5 5M4 15v6h16v-6',
 down:'M5 9l7 7 7-7',book:'M4 3h13a3 3 0 0 1 3 3v16H7a3 3 0 0 1-3-3V3ZM4 17h16M8 7h7M8 11h7'
});
const APP_DEFAULT=()=>({route:'home',tab:'home',tabStacks:{},role:'staff',history:[],selectedStudent:'emma',training:'B',lesson:'active',day:21,query:'',filter:'all',lessons:structuredClone(WF.lessons),documents:structuredClone(WF.documents),draft:structuredClone(WF.draft),savedDraft:null,published:structuredClone(WF.published),draftSaved:false,draftDirty:false,modal:null,modalReturn:null,toast:null,errors:{},availabilityConflict:false,uiState:'normal',readNotifications:[],form:{student:'emma',training:'B',date:'2026-09-23',time:'09:00',duration:'50',place:'Gare · Neuchâtel'},prefs:{appearance:'system',locale:'fr-CH'},scroll:{},pendingNavigation:null});
let A=APP_DEFAULT(),workspaceToastTimer=null;
const staffTabs=[{id:'home',label:'Séance',glyph:'route'},{id:'agenda',label:'Agenda',glyph:'calendar'},{id:'students',label:'Élèves',glyph:'people'},{id:'school',label:'École',glyph:'school'}];
const learnerTabs=[{id:'learner',label:'Mes leçons',glyph:'calendar'},{id:'learner-agenda',label:'Agenda',glyph:'calendar'},{id:'progress',label:'Mon parcours',glyph:'route'}];
const screenTitles={home:'Séance',agenda:'Agenda',students:'Élèves',student:'Dossier élève',lesson:'La leçon',planning:'Planifier',report:'Rédiger le bilan',preview:'Aperçu élève',shared:'Bilan partagé',documents:'Documents',account:'Mon compte',notifications:'Notifications',school:'École',learner:'Mes leçons','learner-agenda':'Agenda',progress:'Mon parcours',components:'Composants communs'};
const learnerAllowed=new Set(['learner','learner-agenda','progress','shared','documents','account','notifications']);
const getStudent=(id=A.selectedStudent)=>WF.students.find(s=>s.id===id)||WF.students[0];
const initials=s=>`<span class="initials" aria-hidden="true">${e(s.initials)}</span>`;
const attr=(action,id='')=>`data-ui="${action}"${id?` data-id="${e(id)}"`:''}`;
const priceForDuration=v=>WF.offerOptions.find(x=>x.duration===Number(v))?.price??0;
const money=v=>new Intl.NumberFormat('fr-CH',{style:'currency',currency:'CHF'}).format(v/100);
const onConnection=()=>!['offline','send-error'].includes(S.environment);
const fact=(label,value)=>`<div class="fact"><dt>${e(label)}</dt><dd>${e(value)}</dd></div>`;
const facts=rows=>`<dl class="ui-facts">${rows.map(x=>fact(...x)).join('')}</dl>`;
const pageTitle=(title,sub='')=>`<div class="page-heading" data-component="DS01"><h1 tabindex="-1" id="workspaceTitle">${e(title)}</h1>${sub?`<p>${sub}</p>`:''}</div>`;
const captions=(text,tone='neutral')=>`<span class="status-caption ${tone}" data-component="DS05">${icon(tone==='success'?'check':tone==='warning'?'attention':'info')}${e(text)}</span>`;
function lessonById(id=A.lesson){return A.lessons.find(l=>l.id===id)||(id==='past18'?WF.completedLesson:WF.completedLesson)}
function nameFor(l){return getStudent(l.student).name}
function lessonLine(l){return UI.lessonRow(l,nameFor(l),attr('lesson',l.id),l.id==='active'&&!S.lessonEnded)}
function personLine(s,selected=false){return UI.row(s.name,`${s.trainings.map(t=>'Permis '+t).join(' · ')} · ${s.next}`,{leading:initials(s),attrs:attr('student',s.id),selected})}
function syncNotice(){if(S.environment==='offline')return UI.state('Hors ligne · données locales','offline');if(S.environment==='send-error')return UI.state('Envoi en échec. Données conservées.','error',`<button ${attr('retry')}>Réessayer</button>`);return ''}
function transient(text){A.toast=text;announce(text);clearTimeout(workspaceToastTimer);render();workspaceToastTimer=setTimeout(()=>{A.toast=null;device.querySelector('.workspace-toast')?.remove()},4200)}
function captureScroll(){const el=device.querySelector('.workspace-body');if(el)A.scroll[A.route]=el.scrollTop}
function go(route,{push=true,focus=true}={}){
 if(A.role==='learner'&&!learnerAllowed.has(route))route='learner';
 captureScroll();if(push&&A.route!==route&&A.route!=='map')A.history.push(A.route);
 if(A.route==='map'){S.playing=false;S.sheet=null;S.pending=null;S.editing=null;}
 A.route=route;A.modal=null;A.errors={};
 if((A.role==='staff'?staffTabs:learnerTabs).some(x=>x.id===route))A.tab=route;
 if(route==='shared'){A.selectedStudent=A.published.student;A.training=A.published.training;}
 render(focus?'#workspaceTitle':null);
}
function navigate(route){if(A.route==='planning'&&A.formTouched){A.pendingNavigation=route;openWorkspaceModal('discard-plan');return}go(route)}
function back(){const to=A.history.pop()||(A.role==='learner'?'learner':'home');go(to,{push:false})}
function openWorkspaceModal(type,extra={}){const trigger=document.activeElement;A.modalReturn=trigger?.dataset?.ui?`[data-ui="${trigger.dataset.ui}"]${trigger.dataset.id?`[data-id="${CSS.escape(trigger.dataset.id)}"]`:''}`:null;A.modal={type,...extra};render('#workspaceDialogTitle');device.querySelector('.workspace-modal button')?.focus({preventScroll:true})}
function closeWorkspaceModal(){const act=A.modalReturn;A.modal=null;A.errors={};render(act||'#workspaceTitle')}
function workspaceHeader(){const isRoot=[...staffTabs,...learnerTabs].some(t=>t.id===A.route);return `<header class="workspace-top" data-component="DS01">${isRoot?`<span class="context">${e(WF.school)}</span>`:`${UI.iconButton('back','Retour',attr('back'))}<span class="context">${e(A.role==='learner'?'Espace élève':'Espace moniteur')}</span>`}<span class="tools">${UI.iconButton('bell','Notifications',attr('go','notifications'))}${UI.iconButton('person','Mon compte',attr('go','account'))}</span></header>`}
function miniTrip(){const pts=F.points.map(p=>({x:12+(p.x-79)/204*275,y:8+(p.y-293)/352*56}));return `<svg class="mini-trip" viewBox="0 0 300 72" fill="none" aria-hidden="true"><path d="${pts.map((p,i)=>`${i?'L':'M'}${p.x} ${p.y}`).join(' ')}" stroke="currentColor" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><circle cx="${pts[0].x}" cy="${pts[0].y}" r="4"/><circle cx="${pts.at(-1).x}" cy="${pts.at(-1).y}" r="5"/></svg>`}
function homePage(){const active=lessonById('active');return pageTitle('Séance','Lundi 21 septembre')+`<section class="hero-lesson" data-component="DS01.lesson-summary"><span class="eyebrow"><span class="state-dot"></span>${S.lessonEnded?'Leçon terminée':stateLabel()}</span><h2>${e(nameFor(active))}</h2><p>Permis B · ${fmt(S.elapsed)}</p>${S.environment==='no-gps'?'':miniTrip()}${UI.button(S.lessonEnded?'Revoir le trajet':'Revenir à la carte',attr('map','capture'),'primary','route')}</section>`+UI.section('Ensuite',A.lessons.filter(l=>l.day===21&&l.id!=='active').slice(0,2).map(lessonLine).join(''),`<button ${attr('go','agenda')}>Tout voir</button>`)+UI.section('À terminer',UI.row('Bilan d’Emma Laurent','18 septembre · Brouillon privé',{glyph:'edit',attrs:attr('go','report')}))}
function agendaPage(learner=false){const lessons=A.lessons.filter(l=>l.day===A.day&&(!learner||l.student==='emma')).sort((a,b)=>a.time.localeCompare(b.time));return pageTitle('Agenda',`Septembre 2026`)+`<div class="day-strip" data-component="DS14" aria-label="Jours de la semaine">${['L','M','M','J','V','S','D'].map((d,i)=>`<button ${attr('day',String(21+i))} aria-label="${21+i} septembre 2026" aria-pressed="${A.day===21+i}"><small>${d}</small>${21+i}</button>`).join('')}</div><div class="agenda-title"><h2 class="page-kicker">${A.day===21?'Lundi':A.day===22?'Mardi':A.day===23?'Mercredi':A.day===24?'Jeudi':A.day===25?'Vendredi':A.day===26?'Samedi':'Dimanche'} ${A.day}</h2>${learner?'':UI.button('Planifier',attr('start-plan'),'quiet','plus')}</div><div id="agendaRows">${lessons.length?lessons.map((l,i)=>`${!learner&&A.day===21&&l.time>='13:00'&&(i===0||lessons[i-1].time<'13:00')?'<div class="day-off">12:00–13:00 · Pause</div>':''}${learner?UI.lessonRow(l,'Leçon de conduite',attr('learner-lesson',l.id)):lessonLine(l)}`).join(''):UI.empty('Aucune leçon ce jour',learner?'Tes engagements apparaîtront ici.':'Choisis un autre jour ou planifie une leçon.',learner?'':UI.button('Planifier',attr('start-plan'),'secondary','plus'))}</div>`}
function filteredStudents(){const query=A.query.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return WF.students.filter(s=>s.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(query)&&(A.filter==='all'||s.trainings.includes(A.filter)))}
function studentsResults(){const list=filteredStudents();return list.length?list.map(s=>personLine(s,A.selectedStudent===s.id&&A.route==='student')).join(''):UI.empty('Aucun résultat','Essaie un autre nom ou retire le filtre.',UI.button('Effacer les filtres',attr('clear-search'),'secondary'))}
function studentsPage(){return pageTitle('Élèves')+UI.search('studentSearch','Rechercher un élève',A.query,'data-input="search"')+`<div class="filter-bar"><button ${attr('filter')} class="${A.filter!=='all'?'active':''}">${icon('filter')}${A.filter==='all'?'Toutes les formations':'Permis '+e(A.filter)}</button>${A.filter!=='all'?`<button class="clear-filter" ${attr('clear-filter')}>Effacer</button>`:''}</div><div id="studentsResults">${studentsResults()}</div>`}
function studentPage(){const s=getStudent(),b=A.training==='B'&&s.id==='emma';const next=A.lessons.find(l=>l.student===s.id&&l.training===A.training);return `<div class="person-intro" data-component="DS01">${initials(s)}<div><h1 id="workspaceTitle" tabindex="-1">${e(s.name)}</h1><p>Élève · ${e(WF.school)}</p></div></div>`+UI.training(s.trainings,A.training,'data-input="training" aria-label="Formation du dossier"')+(next?`<div class="next-lesson">${UI.row(next.id==='active'&&!S.lessonEnded?'Leçon en cours':'Prochaine leçon',`${next.day} septembre · ${next.time} · ${next.duration} min`,{glyph:'calendar',attrs:attr('lesson',next.id)})}</div>`:UI.empty('À planifier',`Pas de leçon pour cette formation.`,UI.button('Planifier',attr('start-plan'),'secondary')))+UI.section('Formation',UI.row('Permis d’élève',A.training==='B'?s.permit:'À vérifier',{glyph:'shield',attrs:attr('permit')})+UI.row('Parcours pédagogique',b?('Dernier bilan · '+A.published.date):'Aucune évaluation publiée',{glyph:'route',attrs:attr('go','progress')}))+UI.section('Suivi',UI.row('Bilans',b?(A.published.date+' · Partagé'):'Aucun bilan pour cette formation',{glyph:'book',attrs:attr('student-reports')})+UI.row('Documents',`${A.documents.filter(d=>d.student===s.id&&d.training===A.training).length} documents`,{glyph:'file',attrs:attr('go','documents')}))+UI.section('Coordonnées',UI.row('Identité et contact','Accès limité à cette école',{glyph:'person',attrs:attr('identity')}))}
function lessonPage(){const l=lessonById(),s=getStudent(l.student),completed=l.state==='COMPLETED'||(l.id==='active'&&S.lessonEnded);return pageTitle(s.name,`Permis ${e(l.training)} · ${completed?'Terminée':l.id==='active'?'En cours':'Planifiée'}`)+facts([['Date',`${l.day} septembre 2026`],['Horaire',`${l.time}–${l.end}`],['Durée prévue',`${l.duration} min`],['Rendez-vous',l.place],['Moniteur',WF.instructor]])+`<div class="page-actions">${l.id==='active'?UI.button(S.lessonEnded?'Revoir le trajet':'Ouvrir la carte',attr('map',S.lessonEnded?'replay':'capture'),'primary','route'):completed?UI.button('Rédiger le bilan',attr('go','report'),'primary','edit'):UI.button('Déplacer',attr('reschedule',l.id),'primary','calendar')}</div>`+UI.section('Avant la leçon',UI.row('Dossier de l’élève',`Permis ${l.training}`,{glyph:'person',attrs:attr('student',s.id)})+UI.row('Permis d’élève',s.permit,{glyph:'shield',attrs:attr('permit')}))+UI.section('Prestation',facts([['Prix convenu',money(l.price)]])+`<p class="section-note">Le temps GPS ne modifie pas le prix convenu.</p>`)}
function planningPage(){const f=A.form;return pageTitle(A.reschedule?'Déplacer':'Planifier',A.reschedule?'La leçon actuelle reste réservée avant confirmation.':'Choisir, puis confirmer.')+(!onConnection()?UI.state('Connexion requise pour réserver. Les champs restent modifiables.','offline'):'')+UI.field('planStudent','Élève',f.student,{options:WF.students.map(s=>({value:s.id,label:s.name})),attrs:'data-form="student"'})+UI.field('planTraining','Formation',f.training,{options:getStudent(f.student).trainings.map(t=>({value:t,label:'Permis '+t})),attrs:'data-form="training"'})+UI.field('planDate','Date',f.date,{type:'date',attrs:'data-form="date" min="2026-09-21" max="2026-09-27"',error:A.errors.date})+UI.field('planTime','Heure',f.time,{type:'time',attrs:'data-form="time"',error:A.errors.time})+UI.field('planDuration','Durée',f.duration,{options:WF.offerOptions.map(x=>({value:String(x.duration),label:x.duration+' minutes'})),attrs:'data-form="duration"'})+UI.field('planPlace','Rendez-vous',f.place,{attrs:'data-form="place" maxlength="160"',error:A.errors.place})+facts([['Moniteur',WF.instructor],['Prix proposé',money(priceForDuration(f.duration))]])+`<p class="section-note">Le prix est confirmé à la réservation. Aucun créneau n’est encore bloqué.</p><div class="page-actions">${UI.button('Vérifier la leçon',attr('review-plan')+(onConnection()?'':' disabled'),'primary')}</div>`}
function saveDraft(){if(S.environment==='save-error'){A.errors.save='Brouillon non enregistré. Le texte est conservé.';render('#workspaceTitle');return false}A.savedDraft=structuredClone(A.draft);A.draftSaved=true;A.draftDirty=false;return true}
function reportPage(){const d=A.draft;return pageTitle('Bilan de leçon',`${icon('lock')}Emma Laurent · B · 18 septembre`)+(A.errors.save?UI.state(A.errors.save,'error'):'')+`<div class="report-fields">${UI.field('workedOn','Travaillé aujourd’hui',d.workedOn,{multiline:true,attrs:'data-draft="workedOn" maxlength="2000"'})}${UI.field('observationText','À retenir',d.observationText,{multiline:true,attrs:'data-draft="observationText" maxlength="4000"'})}${UI.field('nextStep','Prochaine étape',d.nextStep,{multiline:true,attrs:'data-draft="nextStep" maxlength="2000"'})}</div>`+UI.section('Observations à inclure',`<div class="report-selection">${WF.reportObservations.map(x=>UI.observationRow(x,{attrs:attr('include-observation',x.id),selection:true,checked:d.selected.includes(x.id)})).join('')}</div><p class="section-note">Textes sélectionnés uniquement. Aucun trajet ne sera partagé.</p>`)+`<div class="page-actions">${UI.button('Enregistrer',attr('save-draft'),'secondary')}${UI.button('Aperçu élève',attr('preview'),'primary')}</div><p class="ui-caption" id="draftState">${A.draftDirty?'Modifications non enregistrées':A.draftSaved?'Brouillon sur cet appareil · privé':'Brouillon privé'}</p>`}
function reportSnapshot(preview=false){if(!preview)return A.published;return {student:'emma',training:'B',date:'18 septembre 2026',author:WF.instructor,workedOn:A.draft.workedOn,observationText:A.draft.observationText,nextStep:A.draft.nextStep,observations:WF.reportObservations.filter(x=>A.draft.selected.includes(x.id)).map(x=>({id:x.id,second:x.second,theme:x.theme,status:x.status,kind:x.kind,note:x.note,anchor:null})),trajectory:null}}
function reportReadPage(preview=false){const s=reportSnapshot(preview);if(!s)return pageTitle('Bilan')+UI.empty('Aucun bilan partagé','Un bilan apparaîtra après sa publication.');const ready=['workedOn','observationText','nextStep'].every(k=>String(s[k]).trim());return pageTitle(preview?'Aperçu élève':A.role==='learner'?'Ta leçon':'Bilan partagé',`${e(s.date)} · Permis ${e(s.training)}`)+(preview?`<p class="status-caption">${icon('eye')}Non publié · aperçu seulement</p>`:'')+`<article class="document-page" data-component="DS16"><p class="report-byline">${e(getStudent(s.student).name)}<br>${e(s.author)} · ${preview?'Version de travail':'Bilan partagé'}</p><h2>Travaillé aujourd’hui</h2><p>${e(s.workedOn)||'Non renseigné'}</p><h2>À retenir</h2><p>${e(s.observationText)||'Non renseigné'}</p><h2>Prochaine étape</h2><p>${e(s.nextStep)||'Non renseignée'}</p>${s.observations.length?`<h2>Moments à retenir</h2>${s.observations.map(x=>UI.observationRow(x,{readOnly:true,shared:true})).join('')}`:''}</article>`+(preview?`${!ready?UI.state('Complète les trois rubriques avant publication.','error'):''}${!onConnection()?UI.state('Connexion requise pour publier.','offline'):''}<div class="page-actions">${UI.button('Modifier',attr('go','report'),'secondary')}${UI.button('Publier',attr('ask-publish')+(!ready||!onConnection()?' disabled':''),'primary')}</div>`:'')}
function documentsPage(){const list=A.documents.filter(d=>d.student===A.selectedStudent&&d.training===A.training);const state={READY:'Prêt',ANALYZING:'En analyse',REJECTED:'Refusé'};return pageTitle('Documents',`${e(getStudent().name)} · Permis ${e(A.training)}`)+`<div class="page-actions">${UI.button('Ajouter un document',attr('add-document'),'secondary','plus')}</div>`+UI.section('Pièces et supports',list.length?list.map(d=>UI.row(d.name,`${d.type} · ${state[d.status]}${d.humanStatus?' · '+d.humanStatus:''}`,{glyph:d.name.includes('Permis')?'shield':'file',attrs:attr('document',d.id)})).join(''):UI.empty('Aucun document','Les pièces de cette formation apparaîtront ici.'))}
function accountPage(){return pageTitle('Mon compte',A.role==='learner'?'Emma Laurent':WF.instructor)+UI.section('Préférences',`<div class="settings-group">${UI.field('appearance','Apparence',A.prefs.appearance,{options:[{value:'system',label:'Système'},{value:'light',label:'Claire'},{value:'dark',label:'Sombre'}],attrs:'data-pref="appearance"'})}${UI.field('locale','Langue de l’interface',A.prefs.locale,{options:[{value:'fr-CH',label:'Français (Suisse)'}],attrs:'data-pref="locale"',hint:''})}</div>`)+UI.section('Accès',UI.row(WF.school,A.role==='learner'?'Élève':'Moniteur',{glyph:'school',attrs:attr('school-context')})+UI.row('Cet appareil','Session de démonstration',{glyph:'shield',attrs:attr('session-info')}))+UI.section('Vie privée',UI.row('Mes données','Accès, export et demandes',{glyph:'lock',attrs:attr('data-info')})+UI.row('Supprimer mon compte','Compte global, distinct de l’école',{glyph:'trash',attrs:attr('delete-info')}))}
function notificationsPage(){const items=A.role==='learner'?[{id:'bilan',title:'Ton bilan est disponible',meta:'Leçon du 11 septembre',route:'shared'}]:[{id:'draft',title:'Bilan à terminer',meta:'Emma Laurent · 18 septembre',route:'report'},{id:'plan',title:'Leçon planifiée',meta:'Lucas Martin · lundi à 10:15',route:'agenda'}];return pageTitle('Notifications')+items.map(n=>UI.row(n.title,n.meta,{glyph:n.id==='plan'?'calendar':'book',attrs:attr('notification',n.id),trailing:!A.readNotifications.includes(n.id)?'<span class="state-dot" aria-label="Non lue"></span>':''})).join('')}
function schoolPage(){return pageTitle('École',e(WF.school))+UI.row('Votre rôle','Moniteur',{glyph:'shield',action:'read'})+UI.section('Équipe',UI.row(WF.instructor,'Moniteur · votre compte',{glyph:'person',action:'read'})+UI.row('Camille Rey','Administration',{glyph:'person',action:'read'}))+UI.section('Organisation',UI.row('Disponibilités','Lire les créneaux de la semaine',{glyph:'calendar',attrs:attr('availability')})+UI.row('Préférences personnelles','Apparence, langue et données',{glyph:'person',attrs:attr('go','account')}))+`<p class="section-note">Les réglages de l’école sont réservés aux personnes autorisées.</p>`}
function learnerPage(){const next=A.lessons.filter(l=>l.student==='emma').sort((a,b)=>a.day-b.day)[0];return pageTitle('Mes leçons','Emma Laurent')+(next?`<div class="hero-lesson"><span class="eyebrow">${next.id==='active'&&!S.lessonEnded?'Ta leçon en cours':'Ta prochaine leçon'}</span><h2>${next.day} septembre</h2><p>${next.time} · ${next.duration} min · Permis ${next.training}</p>${UI.button('Voir le rendez-vous',attr('learner-lesson',next.id),'primary','calendar')}</div>`:UI.empty('Aucune leçon prévue','Consulte ton agenda pour la suite.'))+UI.section('À préparer',UI.row('Permis d’élève','À emporter à la leçon',{glyph:'shield',attrs:attr('permit')}))+UI.section('Dernier bilan',UI.row(A.published.date,A.published.nextStep,{glyph:'book',attrs:attr('go','shared')}))}
function progressPage(){const valid=A.training==='B'&&A.selectedStudent==='emma';return pageTitle(A.role==='learner'?'Mon parcours':'Parcours pédagogique',`${e(getStudent().name)} · Permis ${e(A.training)}`)+UI.training(getStudent().trainings,A.training,'data-input="training" aria-label="Formation du parcours"')+(valid?WF.skills.map(x=>UI.row(x.title,`${x.value}${x.date?' · '+x.date:''}`,{glyph:x.title==='Stationnement'?'parking':x.title==='Priorités'?'priority':'route',attrs:attr('skill',x.title)})).join(''):UI.empty('Pas encore d’évaluation','Les bilans de cette formation apparaîtront ici.'))+`<p class="section-note">Chaque appréciation garde sa date et son contexte. Aucun score global.</p>`}
function componentsPage(){return pageTitle('Composants','Planche de revue, hors application')+UI.section('DS02 · Actions',`<div class="page-actions">${UI.button('Action principale',attr('sample'),'primary')}${UI.button('Secondaire',attr('sample'),'secondary')}</div>`)+UI.section('DS04 · Même leçon',lessonLine(A.lessons[1]))+UI.section('DS07 · Observation',UI.observationRow(WF.reportObservations[0],{attrs:attr('sample')}))+UI.section('DS03 · Même champ',UI.search('sampleSearch','Rechercher','', 'data-input="sample"')+UI.field('sampleField','Libellé permanent','Texte de démonstration',{attrs:'data-input="sample"'}))+UI.section('DS08 · État',UI.state('Envoi en attente','offline'))}
function renderWorkspaceBody(){const screens={home:homePage,agenda:()=>agendaPage(false),students:studentsPage,student:studentPage,lesson:lessonPage,planning:planningPage,report:reportPage,preview:()=>reportReadPage(true),shared:()=>reportReadPage(false),documents:documentsPage,account:accountPage,notifications:notificationsPage,school:schoolPage,learner:learnerPage,'learner-agenda':()=>agendaPage(true),progress:progressPage,components:componentsPage};if(A.uiState!=='normal'&&!['account','components'].includes(A.route)){let body='';if(A.uiState==='loading')body=`<section class="ui-empty" role="status"><h2>Chargement…</h2><p>Récupération des données.</p></section>`;if(A.uiState==='error')body=UI.empty('Chargement impossible','Aucune donnée n’a été remplacée.',UI.button('Réessayer',attr('retry-page'),'secondary'));if(A.uiState==='empty')body=UI.empty('Rien à afficher ici','Ce n’est pas une erreur de connexion.',UI.button('Revenir aux données',attr('retry-page'),'secondary'));if(A.uiState==='permission')body=UI.empty('Accès indisponible','L’autorisation pour cet espace doit être vérifiée.',UI.button('Mon compte',attr('go','account'),'secondary'));return pageTitle(screenTitles[A.route])+body;}return screens[A.route]?screens[A.route]():homePage()}
function workspaceModal(){const m=A.modal;if(!m)return '';let body='',title='',description='',footer='';
 if(m.type==='filter'){title='Formation';body=[['all','Toutes les formations'],['B','Permis B'],['A','Permis A']].map(([v,t])=>UI.row(t,'',{attrs:attr('set-filter',v),selected:A.filter===v,action:'select',trailing:A.filter===v?icon('check'):''})).join('');}
 if(m.type==='permit'){title='Permis d’élève';body=facts([['Formation','Permis '+A.training],['Contrôle humain',A.training==='B'?getStudent().permit:'À vérifier'],['Pièce','Consulter les documents']])+UI.button('Voir les documents',attr('go','documents'),'secondary','file');description='Un fichier reçu ou prêt à lire n’est pas automatiquement un permis vérifié.';}
 if(m.type==='identity'){title=getStudent().name;body=facts([['École',WF.school],['Formations',getStudent().trainings.join(', ')]]);description='Aucune coordonnée personnelle réelle n’est incluse dans ces données de démonstration.';}
 if(m.type==='review-plan'){title=A.reschedule?'Déplacer cette leçon ?':'Confirmer la leçon ?';body=facts([['Élève',getStudent(A.form.student).name],['Formation','Permis '+A.form.training],['Date',A.form.date],['Heure',A.form.time],['Durée',A.form.duration+' min'],['Lieu',A.form.place],['Prix proposé',money(priceForDuration(A.form.duration))]])+(A.errors.conflict?UI.state(A.errors.conflict,'error'):'');description='Le créneau sera vérifié à nouveau au moment de confirmer.';footer=UI.button(A.reschedule?'Confirmer le déplacement':'Confirmer la leçon',attr('commit-plan')+(!onConnection()?' disabled':''),'primary');}
 if(m.type==='discard-plan'){title='Quitter la planification ?';description='Les modifications non confirmées seront abandonnées. La leçon existante reste inchangée.';body=UI.button('Continuer la saisie',attr('dismiss'),'secondary')+UI.button('Abandonner',attr('discard-plan'),'danger');}
 if(m.type==='publish'){title='Publier ce bilan ?';description='Emma Laurent verra exactement la version prévisualisée. Aucun trajet ni autre observation privée ne sera ajouté.';body=facts([['Destinataire','Emma Laurent · Permis B'],['Leçon','18 septembre 2026'],['Observations',String(A.draft.selected.length)],['Trajet','Non partagé']])+(A.errors.save?UI.state(A.errors.save,'error'):'');footer=UI.button('Publier le bilan',attr('publish')+(!onConnection()?' disabled':''),'primary');}
 if(m.type==='document'){const d=A.documents.find(x=>x.id===m.id);title=d.name;if(d.status==='READY'){body=`<article class="document-thumb"><h3>${e(d.name)}</h3><p>Exemple de document</p><p>${d.name.includes('stationnement')?'Observer, choisir ses repères, puis ajuster la manœuvre.':'Pièce fictive du dossier de formation.'}</p><p>${e(getStudent(d.student).name)} · Permis ${e(d.training)}</p></article>`;description='Aperçu d’un support fictif, sans fichier personnel.'}else description=d.status==='ANALYZING'?'Le fichier est en analyse. Aucun aperçu ni validation humaine n’est disponible.':'Le fichier a été refusé. Il ne peut pas être prévisualisé.';}
 if(m.type==='add-document'){title='Ajouter un document';description='Le nom du fichier est conservé en mémoire de démonstration. Aucun contenu n’est envoyé ni analysé.';body=UI.field('documentUpload','Fichier','',{type:'file',attrs:'accept="image/*,.pdf" data-input="file"'})+`<p class="section-note">Le statut initial sera « En analyse », jamais « Vérifié ».</p>`;}
 if(m.type==='learner-lesson'){const l=lessonById(m.id);title='Ton rendez-vous';body=facts([['Date',`${l.day} septembre 2026`],['Heure',`${l.time}–${l.end}`],['Formation','Permis '+l.training],['Moniteur',WF.instructor],['Lieu',l.place]]);description='Les commandes de capture et les observations privées du moniteur ne sont pas dans ton espace.';}
 if(m.type==='skill'){title=m.id;const evaluated=A.training==='B'&&WF.skills.find(x=>x.title===m.id)?.date;description=evaluated?'Appréciation publiée le 11 septembre, dans le contexte de cette formation. Ce n’est pas une note calculée à partir des signalements.':'Aucune appréciation publiée pour cette compétence dans cette formation. Non observé ne signifie pas zéro.';body=evaluated?UI.button('Lire le bilan source',attr('go','shared'),'secondary','book'):'';}
 if(m.type==='student-reports-empty'){title='Bilans';description='Aucun bilan partagé pour cette formation. Les autres formations ne sont pas mélangées.';}
 if(m.type==='availability'){title='Disponibilités';description='Exemple de semaine du moniteur.';body=facts([['Lundi à vendredi','08:00–17:00'],['Pause','12:00–13:00']])+UI.button('Voir l’agenda',attr('go','agenda'),'secondary','calendar');}
 if(m.type==='school-context'){title='Votre école';body=UI.row(WF.school,A.role==='learner'?'Élève':'Moniteur',{glyph:'school',action:'read'});description='Le changement d’école devra revérifier les accès sans déplacer de données entre écoles.';}
 if(m.type==='session-info'){title='Cet appareil';description='Session de prototype dans ce navigateur. Pas de connexion, de jeton de session ou de compte réel.';}
 if(m.type==='data-info'){title='Mes données';description='L’accès, l’export et la suppression sont des demandes distinctes. Le prototype illustre leur accès depuis le compte ; aucun traitement serveur n’est exécuté.';body=UI.row('Suppression du compte','Accessible même sans école active',{glyph:'trash',attrs:attr('delete-info')});}
 if(m.type==='delete-info'){title='Supprimer mon compte';description='Ce parcours demande une réauthentification et précise les données supprimées ou conservées. La réauthentification et les délais DM06 ne sont pas simulés ici.';body=`<p class="ui-help">Aucune demande réelle ne sera envoyée depuis cette maquette.</p>`;}
 if(m.type==='sample'){title='Composant de référence';description='Même fonction de rendu, mêmes tokens et même comportement sémantique sur chaque écran qui l’utilise.';}
 return UI.modal(title,body,{footer,description});
}
function renderWorkspace(focusSelector=null){applyPrefs();device.dataset.mode='workspace';const inModal=!!A.modal;const body=renderWorkspaceBody();const hasMaster=['student','lesson'].includes(A.route)&&A.role==='staff';device.innerHTML=`${systemBar()}<div class="workspace-base" ${inModal?'inert aria-hidden="true"':''}><div class="workspace">${workspaceHeader()}<div class="workspace-layout">${hasMaster?`<aside class="workspace-master" aria-label="${A.route==='student'?'Liste des élèves':'Leçons'}">${A.route==='student'?filteredStudents().map(s=>personLine(s,s.id===A.selectedStudent)).join(''):A.lessons.map(lessonLine).join('')}</aside>`:''}<div class="workspace-body"><main class="workspace-page">${syncNotice()}${body}</main></div></div></div>${UI.nav(A.role==='learner'?learnerTabs:staffTabs,A.tab)}</div>${workspaceModal()}${A.toast?`<div class="workspace-toast" role="status">${e(A.toast)}</div>`:''}<div class="home-indicator" aria-hidden="true"></div>`;
 const sc=device.querySelector('.workspace-body');if(sc)sc.scrollTop=A.scroll[A.route]||0;
 document.querySelectorAll('[data-screen]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.screen===A.route)));
 document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed','false'));
 document.getElementById('previewTitle').textContent=screenTitles[A.route]||'Drivy';
 if(focusSelector)device.querySelector(focusSelector)?.focus({preventScroll:true});
}
const renderMap=render;render=function(selector=null){if(A.route==='map'){device.dataset.mode='map';renderMap(selector);document.querySelectorAll('[data-screen]').forEach(b=>b.setAttribute('aria-pressed','false'));}else renderWorkspace(selector)};
const switchMap=switchView;switchView=function(v){captureScroll();A.route='map';A.modal=null;A.role='staff';document.getElementById('roleSelect').value='staff';switchMap(v)};
const mapAct=act;act=function(a,b){if(a==='exit'){A.tab='home';go('home',{push:false});return}mapAct(a,b)};
function validatePlan(){const f=A.form;A.errors={};if(!/^2026-09-2[1-7]$/.test(f.date))A.errors.date='Choisis un jour de la semaine de démonstration.';if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(f.time))A.errors.time='Indique une heure valide.';if(!f.place.trim())A.errors.place='Indique le rendez-vous.';return Object.keys(A.errors).length===0}
function commitPlan(){if(!onConnection())return;if(S.environment==='save-error'){A.errors.conflict='Réservation non enregistrée.';render();return}const f=A.form,day=Number(f.date.slice(-2)),[h,m]=f.time.split(':').map(Number),start=h*60+m,end=start+Number(f.duration);const collision=A.lessons.some(l=>{if(l.id===A.reschedule||l.day!==day)return false;const[a,b]=l.time.split(':').map(Number);return start<a*60+b+l.duration&&end>a*60+b});if(A.availabilityConflict||collision||(start<780&&end>720)||start<480||end>1020){A.errors.conflict='Ce créneau n’est plus disponible. Choisis une autre heure.';render();return}const l={id:A.reschedule||'local-'+(A.lessons.length+1),student:f.student,training:f.training,day,time:f.time,end:`${Math.floor(end/60).toString().padStart(2,'0')}:${(end%60).toString().padStart(2,'0')}`,duration:Number(f.duration),place:f.place.trim(),state:'PLANNED',price:priceForDuration(f.duration)};if(A.reschedule)A.lessons=A.lessons.map(x=>x.id===A.reschedule?l:x);else A.lessons.push(l);A.day=day;A.formTouched=false;A.reschedule=null;go('agenda');transient('Leçon confirmée dans la démonstration.')}
function startPlan(id=null){const l=id?lessonById(id):null;A.reschedule=id;A.form=l?{student:l.student,training:l.training,date:`2026-09-${l.day}`,time:l.time,duration:String(l.duration),place:l.place}:{student:A.selectedStudent,training:A.training,date:'2026-09-23',time:'09:00',duration:'50',place:'Gare · Neuchâtel'};A.formTouched=false;go('planning')}
function handleUI(action,id,b){
 switch(action){
 case 'tab':{ if(A.route==='planning'&&A.formTouched){A.pendingNavigation=id;openWorkspaceModal('discard-plan');break} captureScroll(); A.tabStacks[A.tab]={route:A.route,history:[...A.history],selectedStudent:A.selectedStudent,training:A.training,lesson:A.lesson};const saved=A.tabStacks[id];A.tab=id;if(saved){Object.assign(A,saved);go(saved.route,{push:false})}else {A.history=[];go(id,{push:false})}break;}
 case 'go':navigate(id);break;
 case 'back':if(A.route==='planning'&&A.formTouched){A.pendingNavigation=A.history.at(-1)||'agenda';openWorkspaceModal('discard-plan')}else back();break;
 case 'map':switchView(id||'capture');break;
 case 'student':A.selectedStudent=id;A.training=getStudent(id).trainings[0];A.tab='students';go('student');break;
 case 'lesson':A.lesson=id;A.selectedStudent=lessonById(id).student;A.training=lessonById(id).training;go('lesson');break;
 case 'day':A.day=Number(id);A.scroll[A.route]=0;render(`[data-ui=day][data-id="${id}"]`);break;
 case 'start-plan':startPlan();break;
 case 'reschedule':startPlan(id);break;
 case 'review-plan':if(!onConnection())return;if(validatePlan())openWorkspaceModal('review-plan');else render('.ui-field [aria-invalid=true]');break;
 case 'commit-plan':commitPlan();break;
 case 'discard-plan':A.formTouched=false;go(A.pendingNavigation||'agenda',{push:false});break;
 case 'filter':openWorkspaceModal('filter');break;
 case 'set-filter':A.filter=id;closeWorkspaceModal();break;
 case 'clear-filter':A.filter='all';render('[data-ui=filter]');break;
 case 'clear-search':A.query='';A.filter='all';render('#studentSearch');break;
 case 'dismiss':closeWorkspaceModal();break;
 case 'include-observation':{const i=A.draft.selected.indexOf(id);i<0?A.draft.selected.push(id):A.draft.selected.splice(i,1);A.draftDirty=true;captureScroll();render(`[data-ui=include-observation][data-id="${id}"]`);break;}
 case 'save-draft':if(saveDraft())transient('Brouillon enregistré sur cet appareil.');break;
 case 'preview':go('preview');break;
 case 'ask-publish':if(onConnection()&&['workedOn','observationText','nextStep'].every(k=>A.draft[k].trim()))openWorkspaceModal('publish');break;
 case 'publish':if(!onConnection())return;if(!saveDraft())return;A.published=reportSnapshot(true);A.published.id='local-publication';A.publishedAt='SIMULATED';go('shared');transient('Publication simulée. Aucun envoi réel.');break;
 case 'student-reports':if(A.selectedStudent==='emma'&&A.training==='B')go('shared');else openWorkspaceModal('student-reports-empty');break;
 case 'permit':case 'identity':case 'add-document':case 'availability':case 'school-context':case 'session-info':case 'data-info':case 'delete-info':case 'sample':openWorkspaceModal(action);break;
 case 'document':openWorkspaceModal('document',{id});break;
 case 'learner-lesson':openWorkspaceModal('learner-lesson',{id});break;
 case 'skill':openWorkspaceModal('skill',{id});break;
 case 'notification':A.readNotifications.push(id);if(A.role==='learner')go('shared');else if(id==='draft')go('report');else{A.day=21;go('agenda')}break;
 case 'retry':S.environment='normal';render();break;
 case 'retry-page':A.uiState='normal';document.getElementById('pageStateSelect').value='normal';render('#workspaceTitle');break;
 }
}
device.addEventListener('click',ev=>{const b=ev.target.closest('[data-ui]');if(!b||b.disabled)return;ev.preventDefault();captureScroll();handleUI(b.dataset.ui,b.dataset.id,b)});
device.addEventListener('input',ev=>{const b=ev.target;if(b.dataset.draft){A.draft[b.dataset.draft]=b.value;A.draftDirty=true;const note=device.querySelector('#draftState');if(note)note.textContent='Modifications non enregistrées';}if(b.dataset.form){A.form[b.dataset.form]=b.value;A.formTouched=true;}if(b.dataset.input==='search'){A.query=b.value;const el=device.querySelector('#studentsResults');if(el)el.innerHTML=studentsResults()}});
device.addEventListener('change',ev=>{const b=ev.target;if(b.dataset.form==='student'){A.form.training=getStudent(b.value).trainings[0];captureScroll();render('#planTraining')}
 if(b.dataset.input==='training'){A.training=b.value;captureScroll();render('[data-input=training]')}
 if(b.dataset.pref){A.prefs[b.dataset.pref]=b.value;if(b.dataset.pref==='appearance'){S.theme=b.value==='system'?(window.matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):b.value;applyPrefs()}}
 if(b.dataset.input==='file'&&b.files?.length){const f=b.files[0];A.documents.push({id:'local-doc-'+A.documents.length,student:A.selectedStudent,training:A.training,name:f.name,type:f.type.includes('pdf')?'PDF':'Fichier',status:'ANALYZING',humanStatus:null});closeWorkspaceModal();transient('Fichier ajouté en mémoire · analyse non exécutée.')}});
device.addEventListener('keydown',ev=>{if(!A.modal)return;const dialog=device.querySelector('.workspace-modal .sheet');if(!dialog)return;if(ev.key==='Escape'){ev.preventDefault();closeWorkspaceModal()}if(ev.key==='Tab'){const xs=[...dialog.querySelectorAll('button,input,select,textarea,[tabindex="0"]')].filter(x=>!x.disabled&&!x.hidden);if(!xs.length)return;const first=xs[0],last=xs.at(-1);if(ev.shiftKey&&document.activeElement===first){ev.preventDefault();last.focus()}else if(!ev.shiftKey&&document.activeElement===last){ev.preventDefault();first.focus()}}});
function setRole(role){A.role=role==='learner'?'learner':'staff';A.history=[];A.tabStacks={};A.selectedStudent='emma';A.training='B';A.modal=null;S.sheet=null;S.playing=false;document.getElementById('roleSelect').value=A.role;go(A.role==='learner'?'learner':'home',{push:false})}
document.querySelectorAll('[data-screen]').forEach(b=>b.addEventListener('click',()=>{if(!learnerAllowed.has(b.dataset.screen)&&A.role==='learner')setRole('staff');go(b.dataset.screen)}));
document.getElementById('roleSelect').addEventListener('change',ev=>setRole(ev.target.value));
document.getElementById('pageStateSelect').addEventListener('change',ev=>{A.uiState=ev.target.value;render()});
document.getElementById('planConflict').addEventListener('change',ev=>{A.availabilityConflict=ev.target.checked});
document.getElementById('resetDemo').addEventListener('click',()=>{A=APP_DEFAULT();document.getElementById('pageStateSelect').value='normal';document.getElementById('roleSelect').value='staff';document.getElementById('planConflict').checked=false;go('home',{push:false})});
window.drivy.view=switchView;
window.drivy.app={state:()=>structuredClone(A),show:r=>go(r,{push:false}),role:setRole,set:patch=>{Object.assign(A,patch);render()},fixtures:WF,registry:Object.keys(UI)};
if(params.get('screen')){const start=params.get('screen');if(['learner','learner-agenda'].includes(start)||params.get('role')==='learner')setRole('learner');go(start,{push:false,focus:false});}else if('__START_SCREEN__'==='home')go('home',{push:false,focus:false});else {A.route='map';render();}
